### ISSUE TITLE
Always skips build on project that doesn't have a deploy?

### ISSUE THREAD

**Issue by jaydiablo** [f22hd/netlify-plugin-nx-skip-build#7]
**Describe the bug**

We're testing this plugin with Netlify and Nx, and it seems to work fine for sites that have already had a deploy before adding this plugin, but for a new site it doesn't seem to allow any builds through.  I'm assuming that this is because `nx print-affected` isn't getting a base commit? The base commit comes from `process.env.CACHED_COMMIT_REF` but is there a chance that this environment variable isn't set to anything when the site hasn't had a successful build?

If it's not set, it seems that the `nx print-affected` command will throw an error (with exit code 1). If the command fails, does execution continue as if the project is unaffected?

**Steps to reproduce**

I believe this happens just to new sites that haven't had a successful build when the plugin runs, but haven't confirmed.

**Expected behavior**

I'd expect the plugin to allow the build to finish if the `nx print-affected` command fails for any reason.

I'll try to deploy a local version of the plugin to test further.

**Comment by f22hd** [comment]
thank you @jaydiablo for your detailed comment. I will reproduce it to resolve the issue.

**Comment by f22hd** [comment]
Update, after doing investigations, 
`process.env.CACHED_COMMIT_REF`returning the latest commit that equals `HEAD` for any new app for the first deployment.
so the command `nx print-affected` doesn't notice any changes, for this reason, the build was skipped.

**Comment by f22hd** [comment]
@jaydiablo the issue has been resolved, make sure to update the package to the latest version.
https://www.npmjs.com/package/netlify-plugin-nx-skip-build

**Comment by f22hd** [comment]
@jaydiablo the issue has been resolved, make sure to update the package to the latest version.
https://www.npmjs.com/package/netlify-plugin-nx-skip-build

**Comment by jaydiablo** [comment]
Thank you!
